---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution in ["Mint", "Ubuntu"]

  - name: install apache2 package
    apt:
      name: apache2
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Mint" "Ubuntu"]

  - name: update repository index
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install httpd package
    dnf:
      name: httpd
      name: php
      state: latest
    when: ansible_distribution == "CentOS"



